alias: Oil Radiator - Free/Negative ComEd Price
description: ""
triggers:
  - trigger: state
    entity_id: sensor.comed_current_hour_average_price
  - trigger: homeassistant
    event: start
  - trigger: state
    entity_id: input_select.ac_override_mode
    id: override_changed
actions:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.comed_current_hour_average_price
            below: 0
            alias: ComEd Hourly < 0 cents
          - condition: numeric_state
            entity_id: weather.forecast_home
            below: 60
            attribute: temperature
            alias: Outside temperature < 60
          - condition: state
            entity_id: input_select.ac_override_mode
            state:
              - comfort
              - none
        sequence:
          - alias: Radiator on
            action: switch.turn_on
            data: {}
            target:
              entity_id: switch.radiator_outlet
        alias: Free electricity and cold outside, radiator on
    default:
      - alias: Radiator off
        action: switch.turn_off
        data: {}
        target:
          entity_id: switch.radiator_outlet
